[tool.poetry]
name = "bidsificator"
version = "1.12.0"
description = ""
authors = ["Florian Sipp <florian.sipp@chuv.ch>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
pyqt6 = "^6.10.2"

# bids
numpy = "^2.4"
pandas = "^2.3"
dicom2nifti = ">=2.6.2"
bids_validator = ">=1.14.5"

# neurophysiology data conversion
mne = "^1.11.0"
neo = "^0.14.3"
edfio = "^0.4.12"
pybv = "^0.7.6"

# API
flasgger = "^0.9.7"
flask = "^3.1"
flask-cors = "^6.0"
flask-httpauth = "^4.8"
flask-restful = "^0.3.10"
flask_caching = "^2.3.1"
openpyxl = "^3.1.5"

[tool.poetry.scripts]
bidsificator = "bidsificator.main:main"
bidsificator-api = "bidsificator.api:main"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.codespell]
# Ref: https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git*,*.lock,./bidsificator/schema/bids_schema.json'
check-hidden = true
# ignore-regex = ''
ignore-words-list = 'nd'  # 'nd' is a valid BIDS value meaning "not determined"
