# Form implementation generated from reading ui file 'bidsificator/forms/ParticipantsTab.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ParticipantsTab(object):
    def setupUi(self, ParticipantsTab):
        ParticipantsTab.setObjectName("ParticipantsTab")
        ParticipantsTab.resize(600, 500)
        self.gridLayout_2 = QtWidgets.QGridLayout(ParticipantsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CreateSubjectLayout = QtWidgets.QHBoxLayout()
        self.CreateSubjectLayout.setObjectName("CreateSubjectLayout")
        self.SubjectLineEdit = QtWidgets.QLineEdit(parent=ParticipantsTab)
        self.SubjectLineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.SubjectLineEdit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.SubjectLineEdit.setInputMask("")
        self.SubjectLineEdit.setText("")
        self.SubjectLineEdit.setMaxLength(32767)
        self.SubjectLineEdit.setCursorPosition(0)
        self.SubjectLineEdit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
        self.SubjectLineEdit.setObjectName("SubjectLineEdit")
        self.CreateSubjectLayout.addWidget(self.SubjectLineEdit)
        self.CreateSubjectPushButton = QtWidgets.QPushButton(parent=ParticipantsTab)
        self.CreateSubjectPushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.CreateSubjectPushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.CreateSubjectPushButton.setObjectName("CreateSubjectPushButton")
        self.CreateSubjectLayout.addWidget(self.CreateSubjectPushButton)
        self.gridLayout_2.addLayout(self.CreateSubjectLayout, 0, 0, 1, 1)
        self.tableWidget = PatientTableWidget(parent=ParticipantsTab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 1)

        self.retranslateUi(ParticipantsTab)
        QtCore.QMetaObject.connectSlotsByName(ParticipantsTab)

    def retranslateUi(self, ParticipantsTab):
        _translate = QtCore.QCoreApplication.translate
        ParticipantsTab.setWindowTitle(_translate("ParticipantsTab", "Participants"))
        self.SubjectLineEdit.setPlaceholderText(_translate("ParticipantsTab", "sub-<IDENTIFIER123>"))
        self.CreateSubjectPushButton.setText(_translate("ParticipantsTab", "Create Subject"))
from ..ui.PatientTableWidget import PatientTableWidget
