# Form implementation generated from reading ui file 'bidsificator/forms/ValidationResultsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ValidationResultsDialog(object):
    def setupUi(self, ValidationResultsDialog):
        ValidationResultsDialog.setObjectName("ValidationResultsDialog")
        ValidationResultsDialog.resize(900, 600)
        ValidationResultsDialog.setModal(True)
        self.mainLayout = QtWidgets.QVBoxLayout(ValidationResultsDialog)
        self.mainLayout.setObjectName("mainLayout")
        self.summaryLabel = QtWidgets.QLabel(parent=ValidationResultsDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.summaryLabel.setFont(font)
        self.summaryLabel.setObjectName("summaryLabel")
        self.mainLayout.addWidget(self.summaryLabel)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setObjectName("statsLayout")
        self.errorButton = QtWidgets.QPushButton(parent=ValidationResultsDialog)
        self.errorButton.setCheckable(True)
        self.errorButton.setChecked(True)
        self.errorButton.setObjectName("errorButton")
        self.statsLayout.addWidget(self.errorButton)
        self.warningButton = QtWidgets.QPushButton(parent=ValidationResultsDialog)
        self.warningButton.setCheckable(True)
        self.warningButton.setChecked(True)
        self.warningButton.setObjectName("warningButton")
        self.statsLayout.addWidget(self.warningButton)
        self.infoButton = QtWidgets.QPushButton(parent=ValidationResultsDialog)
        self.infoButton.setCheckable(True)
        self.infoButton.setChecked(True)
        self.infoButton.setObjectName("infoButton")
        self.statsLayout.addWidget(self.infoButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.statsLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.statsLayout)
        self.splitter = QtWidgets.QSplitter(parent=ValidationResultsDialog)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.splitter)
        self.treeWidget.setColumnCount(3)
        self.treeWidget.setObjectName("treeWidget")
        self.detailsText = QtWidgets.QTextEdit(parent=self.splitter)
        self.detailsText.setMaximumSize(QtCore.QSize(16777215, 150))
        self.detailsText.setReadOnly(True)
        self.detailsText.setObjectName("detailsText")
        self.mainLayout.addWidget(self.splitter)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.exportButton = QtWidgets.QPushButton(parent=ValidationResultsDialog)
        self.exportButton.setObjectName("exportButton")
        self.buttonLayout.addWidget(self.exportButton)
        self.closeButton = QtWidgets.QPushButton(parent=ValidationResultsDialog)
        self.closeButton.setDefault(True)
        self.closeButton.setObjectName("closeButton")
        self.buttonLayout.addWidget(self.closeButton)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(ValidationResultsDialog)
        QtCore.QMetaObject.connectSlotsByName(ValidationResultsDialog)

    def retranslateUi(self, ValidationResultsDialog):
        _translate = QtCore.QCoreApplication.translate
        ValidationResultsDialog.setWindowTitle(_translate("ValidationResultsDialog", "BIDS Validation Results"))
        self.summaryLabel.setText(_translate("ValidationResultsDialog", "Dataset Status"))
        self.errorButton.setText(_translate("ValidationResultsDialog", "❌ Errors: 0"))
        self.warningButton.setText(_translate("ValidationResultsDialog", "⚠️ Warnings: 0"))
        self.infoButton.setText(_translate("ValidationResultsDialog", "ℹ️ Info: 0"))
        self.treeWidget.headerItem().setText(0, _translate("ValidationResultsDialog", "Type"))
        self.treeWidget.headerItem().setText(1, _translate("ValidationResultsDialog", "Location"))
        self.treeWidget.headerItem().setText(2, _translate("ValidationResultsDialog", "Message"))
        self.exportButton.setText(_translate("ValidationResultsDialog", "Export Report"))
        self.closeButton.setText(_translate("ValidationResultsDialog", "Close"))
